-- In production comment drop stat and add 'IF NOT EXISTS' after CREATE <TYPE_NAME>

DROP TABLE IF EXISTS entity;  
DROP SEQUENCE IF EXISTS seq_entity;

-- CREATE SEQUENCE IF NOT EXISTS
CREATE SEQUENCE seq_entity_ids;

--CREATE TABLE IF NOT EXISTS
CREATE TABLE Entity (  
  ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_entity_ids'),
  Name VARCHAR(128)  UNIQUE NOT NULL,
  Descr VARCHAR(1024),
  Created TIMESTAMP WITH TIME ZONE NOT NULL,
  Last_updated TIMESTAMP WITH TIME ZONE NOT NULL,
  Last_operator VARCHAR(128) NOT NULL
);